Avoid deprecated API overwrite new API
rhysd/promised-neovim-client pull request #2
Opened 2016-11-26 10:38 UTC by chemzqm

Neovim have deprecated API,  for example : 
``` yaml
- method: false
  name: nvim_ui_attach
  parameters:
  - [Integer, width]
  - [Integer, height]
  - [Dictionary, options]
  return_type: void
  since: 1
- deprecated_since: 1
  method: false
  name: ui_attach
  parameters:
  - [Integer, width]
  - [Integer, height]
  - [Boolean, enable_rgb]
  return_type: void
  since: 0
```
Current implementation could overwrite the newer API with deprecated ones, like `ui_attach`

<img width="1194" alt="screen shot 2016-11-26 at 8 03 06 am" src="https://cloud.githubusercontent.com/assets/251450/20639758/1fdc0f56-b407-11e6-8833-89c796947f67.png">

2016-11-26 16:17 UTC, rhysd requested changes

2016-11-26 16:17 UTC, rhysd commented on index.js
> +        if (func.deprecated_since && Type.prototype.hasOwnProperty(methodName)) continue
Could you fix style?

```js
if (func.deprecated_since && Type.prototype.hasOwnProperty(methodName)) {
    continue;
}
```

2016-11-26 16:18 UTC, rhysd commented
@chemzqm 

Thank you for catching it. Please check the review comment.

2016-11-27 01:11 UTC, chemzqm commented on index.js
> +        if (func.deprecated_since && Type.prototype.hasOwnProperty(methodName)) continue
sure

2016-11-27 01:12 UTC, chemzqm commented
@rhysd fixed

2016-11-27 04:04 UTC, merged